name: nhentai_app
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  blur: ^3.1.0
  cached_network_image: ^3.2.2
  collection: ^1.16.0
  core_mixins: ^1.0.2
  cupertino_icons: ^1.0.2
  domain_verification_manager: ^1.0.0
  dynamic_layouts:
    path: ../dynamic_layouts
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_cache_manager: ^3.3.0
  flutter_settings_screens: ^0.3.3-null-safety+2
  go_router: ^13.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  intl: ^0.19.0
  nhentai:
    git:
      url: https://github.com/LacticWhale/nhentai_dart.git
  ordered_set: ^5.0.0
  package_info_plus: ^6.0.0
  pasteboard: ^0.2.0
  path: ^1.8.1
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  preload_page_view: ^0.2.0
  socks5_proxy: ^1.0.2
  uni_links: ^0.5.1
  webview_cookie_manager: ^2.0.6
  webview_flutter: ^4.7.0

dev_dependencies:
  zekfad_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
