---
name: "tagged-release"

on:
  push:
    branch:
      - "master"
    tags:
      - "v*.*.*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    # if: "startsWith(github.event.head_commit.message, 'feat') && "

    steps:
      - uses: "actions/checkout@v3"
      
      - uses: "actions/setup-java@v2"
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: "subosito/flutter-action@v2"
        with:
          flutter-version: '3.3.8'

      - id: decode_keystore
        uses: "timheuer/base64-to-file@v1.2"
        with:
          fileName: '/keystroke/temp_file.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - run: echo ${{ steps.decode_keystore.outputs.filePath }}
      - run: flutter pub get
      
      - run: flutter build apk --release --no-sound-null-safety
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/app/outputs/flutter-apk/app-release.apk
